#!/bin/sh -e

# Was previous step completed?
if [ ! -f installed.dbservers ]; then
	echo "Database servers were not initialized - run previous script" >&2
	exit 1
fi

# Was this step already completed?
if [ -f installed.sudoers ]; then
	echo "sudoers already configured - skipping."
	exit 0
fi

./install-sudoers

echo "sudoers configured OK"
touch installed.sudoers

