#!/bin/sh -e

##Fusion 2012 fullinstall script 

# Set up system variables
./init.sh
. ./fusion-sys.cfg

# Explicitly set umask
umask 0022

# Install log
log="install.log"

# Installation is interactive by default
export INTERACTIVE="True"

usage() {
	fmt -s -w $(tput cols) <<-EOF

		Nagios Fusion installer script
		Copyright 2009-2012, Nagios Enterprises LLC.
		License:
		    Nagios Software License <http://assets.nagios.com/licenses/nagios_software_license.txt>
		Support:
		    Fusion Support Mailing List <xisupport@nagios.com> (customers only)
		    Community Forums <http://support.nagios.com/forum/>

		Usage: fullinstall [options...]

		Options:
		    -h | --help
		        Display this help text
		    -n | --non-interactive
		        Assume defaults for all questions (for scripted installs)
		    -v | --version
		        Show the version of Fusion to be installed (and existing version, for upgrades)

		IMPORTANT: This script should only be used on a 'clean' install of CentOS or RedHat.  Do NOT use this on a system that has been tasked with other purposes or has an existing install of Nagios Core.  To create such a clean install you should have selected ONLY the 'Base' package in the OS installer.

	EOF
}


# Wrapper function for installation scripts
run_sub() {
	echo "Running '$1'..."

	# Run the command and copy output to installer log
	# Fail file is a portable bourne shell alternative to $PIPESTATUS
	FAILFILE=".fail-$$"
	rm -f "$FAILFILE"
	(eval "$@" 2>&1 || echo $? > "$FAILFILE") | tee -a "$log"
	echo "RESULT=$(cat "$FAILFILE" 2>/dev/null || echo 0)"
	if [ -f "$FAILFILE" ]; then
		cat >&2 <<-EOF

			===================
			INSTALLATION ERROR!
			===================
			Installation step failed - exiting.
			Check for error messages in the install log (install.log).

			If you require assistance in resolving the issue, please include install.log
			in your communications with Nagios Fusion technical support.

			The script that failed was: '$1'
		EOF
		exit 1
	fi
	rm -f "$FAILFILE"
}



path_is_ok() {
        echo "$PATH" \
        | awk 'BEGIN{RS=":"} {p[$0]++} END{if (p["/sbin"] && p["/usr/sbin"]) exit(0); exit(1)}'
}

if ! path_is_ok; then
        echo "Your system \$PATH does not include /sbin and /usr/sbin.  This is usually the result of installing GNOME rather than creating a clean system."
        echo "Adding /sbin and /usr/sbin to \$PATH."
        PATH="$PATH:/usr/sbin:/sbin"
fi

# Parse command line
while [ -n "$1" ]; do
	case "$1" in
		-h | --help)
			usage
			exit 0
			;;
		-v | --version)
			sed -n '/full/ s/.*=//p' "${0%/*}/nagiosfusion/basedir/var/fusionversion"
			exit 0
			;;
		-n | --non-interactive)
			export INTERACTIVE="False"
			;;
		*)
			echo "Unknown option:  $1" >&2
			usage >&2
			exit 1
	esac
	shift
done

if [ "$INTERACTIVE" = "True" ]; then
	fmt -s -w $(tput cols) <<-EOF
		========================
		Nagios Fusion Full Installer
		========================

		This script will do a complete install of Nagios Fusion by executing all necessary sub-scripts.

		IMPORTANT: This script should only be used on a 'clean' install of CentOS or RedHat.  Do NOT use this on a system that has been tasked with other purposes or has an existing install of Nagios Core.  To create such a clean install you should have selected ONLY the 'Base' package in the OS installer.
	EOF
	read -p "Do you want to continue? [Y/n] " res

	case "$res" in
		Y | y | "")
			echo "Proceeding with installation..."
			;;
		*)
			echo "Installation cancelled"
			exit 0
	esac
fi


# Initialize install.log
cat >>"$log" <<-EOF
	Nagios Fusion Installation Log
	==========================
	DATE: $(date)

	DISTRO INFO:
	$distro
	$version
	$architecture

EOF

{
if [ ! -f /usr/local/nagiosfusion/var/fusionversion ]; then
	echo "THIS IS A NEW INSTALL!"
else
	echo "THIS IS AN UPGRADE!"
	echo
	echo "OLD VERSION:"
	grep -v "#" /usr/local/nagiosfusion/var/fusionversion
fi
echo
echo "INSTALLING:"
grep -v "#" nagiosfusion/basedir/var/fusionversion
echo
} >>"$log"


# Install the subcomponents
run_sub ./0-yum noupdate
run_sub ./1-prereqs
run_sub ./2-usersgroups
run_sub ./3-dbservers
run_sub ./5-sudoers
run_sub ./6-firewall
run_sub ./8-selinux
run_sub ./11-sourceguardian
run_sub ./B-installfusion
run_sub ./C-cronjobs
run_sub ./D-chkconfigalldaemons
run_sub ./F-startdaemons
run_sub ./Z-webroot

echo >>"$log"
echo "Install complete!" >>"$log"

if [ $ver -eq 7 ]; then
	ip=$(ip addr | egrep -1 ens[0-9][0-9] | grep -m 1 'inet' | awk '/inet[^6]/{print substr($2,0)}' | sed 's|/.*||')
else
	ip=$(ifconfig | egrep -1 eth[0-9] | grep -m 1 'inet' | awk '/inet[^6]/{print substr($2,6)}')
fi

cat <<-EOF

	Nagios Fusion Installation Complete!

	You can access the Nagios Fusion web interface by visiting:
	    http://${ip}/nagiosfusion/

EOF

