#!/bin/sh -e

# Remove old sudoers entries
grep -v NAGIOSFUSION /etc/sudoers > /etc/sudoers.new
mv -f /etc/sudoers.new /etc/sudoers

# Remove TTY requirement
sed -i 's/Defaults    requiretty/#Defaults    requiretty/g' /etc/sudoers

# Add new sudoers entries
cat nagiosfusion/nagiosfusion.sudoers >> /etc/sudoers

# Set permissions
chmod 440 /etc/sudoers